services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - JIRA_BASE_URL
      - JIRA_PASSWORD
      - JIRA_LOGIN
      - FPC_LISTEN_ADDRESS=:3000